# app/utils/enums.py

from enum import Enum


class UserRole(str, Enum):
    CUSTOMER = "customer"
    DRIVER = "driver"


class RideStatus(str, Enum):
    REQUESTED = "REQUESTED"
    SEARCHING_DRIVER = "SEARCHING_DRIVER"
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED"
    DRIVER_ARRIVING = "DRIVER_ARRIVING"
    DRIVER_ARRIVED = "DRIVER_ARRIVED"
    RIDE_STARTED = "RIDE_STARTED"
    RIDE_COMPLETED = "RIDE_COMPLETED"
    CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER"
    CANCELLED_BY_DRIVER = "CANCELLED_BY_DRIVER"
    EXPIRED = "EXPIRED"