# app/websocket/events.py

class WsEvent:
    AUTH_SUCCESS = "AUTH_SUCCESS"
    AUTH_ERROR = "AUTH_ERROR"

    NEW_RIDE_REQUEST = "NEW_RIDE_REQUEST"
    RIDE_ACCEPTED = "RIDE_ACCEPTED"
    RIDE_STATUS_CHANGED = "RIDE_STATUS_CHANGED"
    RIDE_CANCELLED = "RIDE_CANCELLED"

    DRIVER_LOCATION = "DRIVER_LOCATION"

    INFO = "INFO"
    ERROR = "ERROR"
    PING = "PING"
    PONG = "PONG"